{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: bananflix
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount | default 3 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $name }}-{{ $svc.image.env }}"
      imagePullSecrets:
        - name: regcred
          ports:
            - containerPort: {{ $svc.service.port }}
          resources:
            {{- $res := default $.Values.resources $svc.resources }}
            limits:
              cpu: {{ $res.limits.cpu }}
              memory: {{ $res.limits.memory }}
            requests:
              cpu: {{ $res.requests.cpu }}
              memory: {{ $res.requests.memory }}
---
{{- end }}