{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: bananflix
  labels:
    app: {{ $name }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}
      protocol: TCP
  selector:
    app: {{ $name }}
---
{{- end }}