replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8001
  targetPort: 8001
resources:
  limits:
    cpu: "180m"
    memory: "512Mi"
  requests:
    cpu: "160m"
    memory: "256Mi"
ingress:
  enabled: false