replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 6379
  targetPort: 6379
resources:
  limits:
    cpu: "110m"
    memory: "512Mi"
  requests:
    cpu: "90m"
    memory: "256Mi"
ingress:
  enabled: false