replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8003
  targetPort: 8003
resources:
  limits:
    cpu: "110m"
    memory: "512Mi"
  requests:
    cpu: "80m"
    memory: "256Mi"
ingress:
  enabled: false