replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5173
resources:
  limits:
    cpu: "100m"
    memory: "512Mi"
  requests:
    cpu: "80m"
    memory: "256Mi"
ingress:
  enabled: false