replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5432
resources:
  limits:
    cpu: "320m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
ingress:
  enabled: false