replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8005
resources:
  limits:
    cpu: "140m"
    memory: "512Mi"
  requests:
    cpu: "120m"
    memory: "256Mi"
ingress:
  enabled: false