name: Build and Push Stats Service Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'stats/**'
      - '.github/**'

env:
  STATS_IMAGE_NAME: stats-service
  DOCKER_PRIVATE_REGISTRY: bananaflix

jobs:
  build-and-push-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./stats
          file: ./stats/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_PRIVATE_REGISTRY }}:${{ env.STATS_IMAGE_NAME }}-${{ github.ref_name }}
