name: Build and Push Upload Service Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'upload/**'
      - '.github/**'

env:
  UPLOAD_IMAGE_NAME: upload-service
  DOCKER_PRIVATE_REGISTRY: bananaflix

jobs:
  build-and-push-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./upload
          file: ./upload/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_PRIVATE_REGISTRY }}:${{ env.UPLOAD_IMAGE_NAME }}-${{ github.ref_name }}
