name: Build and Push Video Convert Service Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'video-convert/**'
      - '.github/**'

env:
  VIDEO_CONVERT_IMAGE_NAME: video-convert-service
  DOCKER_PRIVATE_REGISTRY: bananaflix

jobs:
  build-and-push-video-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./video-convert
          file: ./video-convert/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_PRIVATE_REGISTRY }}:${{ env.VIDEO_CONVERT_IMAGE_NAME }}-${{ github.ref_name }}
