replicaCount: 2
image:
  repository: bananaflix
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 1883
  targetPort: 1883
resources:
  limits:
    cpu: "60m"
    memory: "512Mi"
  requests:
    cpu: "40m"
    memory: "256Mi"
ingress:
  enabled: false